version: "3.4"

services:
  webapp:
    image: "blogs/ui-be:20230711-7c49f0ac"
    restart: unless-stopped
    environment:
    - MYSQL_HOST=mysql
    volumes:
      - "./.env:/app/.env"
    depends_on:
      - mysql
    ports:
      - "3080:3080"
  mysql:
    image: mysql:5.7
    restart: always
    environment:
    - MYSQL_DATABASE=blogs
    - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - "3609:3306"

